### PR TITLE
 fix hanging issue on new pluto...

### PR DESCRIPTION
**Pull request by fonsp**

### CODE REVIEW

**Comment by greimel** [comment]
Thanks! Though, I can't see the link between the name of the PR and the changes. Is there a mistake somewhere?

Did you mean to add a Manifest?

**Comment by fonsp** [comment]
Oh weird, that must have been generated because of all the forking and branching

**Comment by greimel** [comment]
It seems that a similar fix is needed to use `Franklin.optimize()`.

But I still don't get the notebook run properly.

The cell that serves the website locally now runs forever. (see screen recording below) Any ideas what's going on?

https://user-images.githubusercontent.com/6280307/158083130-964c451d-2d3e-438d-8a1a-dd12eaf0e4c3.mov

**Comment by greimel** [comment]
follow-up PR: #12

**Pull request merged**
